// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSddXtAb1kApC9PIGAyurS-G6dLXwOCz8',
    appId: '1:478391684566:web:6c1f9d3c75cdc757b6a877',
    messagingSenderId: '478391684566',
    projectId: 'barcodetracking-c86a7',
    authDomain: 'barcodetracking-c86a7.firebaseapp.com',
    storageBucket: 'barcodetracking-c86a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbLE-XSFvJF96_5jiCVs_799fwwZENCiM',
    appId: '1:478391684566:android:2c7c408b666d2ca4b6a877',
    messagingSenderId: '478391684566',
    projectId: 'barcodetracking-c86a7',
    storageBucket: 'barcodetracking-c86a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1P6bAS6Ejhq6yifemGtEMQYvm63QBZc',
    appId: '1:478391684566:ios:c9128b39a4c521bdb6a877',
    messagingSenderId: '478391684566',
    projectId: 'barcodetracking-c86a7',
    storageBucket: 'barcodetracking-c86a7.appspot.com',
    iosClientId:
        '478391684566-85tmuk8svnv89qsln4hikgpbhdjbnojb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rekatracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb1P6bAS6Ejhq6yifemGtEMQYvm63QBZc',
    appId: '1:478391684566:ios:0196228b94d56b9fb6a877',
    messagingSenderId: '478391684566',
    projectId: 'barcodetracking-c86a7',
    storageBucket: 'barcodetracking-c86a7.appspot.com',
    iosClientId:
        '478391684566-jn48s7foup40i4bai4jmdb3qo1efdkfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rekatracking.RunnerTests',
  );
}
